import test from "node:test";
import assert from "node:assert/strict";
import fs from "fs";
import path from "path";
import { isPlaceholderCv, REPO_ROOT } from "../config-utils.mjs";
import { generateStarterCv } from "../setup-wizard.mjs";

test("CV Check: Empty, null, or short CV strings are flagged as placeholder", () => {
  assert.strictEqual(isPlaceholderCv(null), true);
  assert.strictEqual(isPlaceholderCv(""), true);
  assert.strictEqual(isPlaceholderCv("   "), true);
  assert.strictEqual(isPlaceholderCv("Short CV text that is under 200 characters long."), true);
});

test("CV Check: Starter template generated by wizard is flagged as placeholder", () => {
  const starter = generateStarterCv("Jane Doe", ["Backend Engineer"]);
  assert.strictEqual(isPlaceholderCv(starter), true);
});

test("CV Check: cv.example.md is flagged as placeholder", () => {
  const exampleCvPath = path.resolve(REPO_ROOT, "cv.example.md");
  assert.strictEqual(fs.existsSync(exampleCvPath), true);
  const content = fs.readFileSync(exampleCvPath, "utf8");
  assert.strictEqual(isPlaceholderCv(content), true);
});

test("CV Check: Real detailed CV passes placeholder check", () => {
  const realCv = `
# Jane Doe
**Senior Full Stack Engineer**
Email: jane.doe@example.com | Phone: +91 9876543210 | Location: Bengaluru, India
GitHub: github.com/janedoe | LinkedIn: linkedin.com/in/janedoe

## Professional Summary
Software Engineer with 3+ years of experience designing scalable microservices, backend RESTful APIs, and responsive frontends. Experienced in Node.js, TypeScript, PostgreSQL, and React. Passionate about automated testing, CI/CD, and performance profiling.

## Technical Skills
- Languages: JavaScript, TypeScript, Python, SQL
- Technologies: React, Next.js, Express, Docker, Redis, PostgreSQL, Git

## Experience
### Software Engineer - Tech Solutions Pvt Ltd (2022 - Present)
- Designed and maintained high-throughput payment webhook processing service handling 2M requests/day.
- Reduced database p95 query latency by 35% through query optimization and Redis caching layer.
- Implemented comprehensive unit and integration test coverage using Node test runner.

## Education
B.Tech in Computer Science, State University, 2018 - 2022
`;

  assert.strictEqual(isPlaceholderCv(realCv), false);
});

test("CV Check: Real CV containing any [[...]] placeholder prompt fails placeholder check", () => {
  const almostReal = `
# Jane Doe
**Senior Full Stack Engineer**
Email: jane.doe@example.com | Phone: +91 9876543210 | Location: Bengaluru, India

## Professional Summary
Experienced software engineer with real project details and background.

## Technical Skills
- Languages: JavaScript, TypeScript, Python, SQL
- [[ADD REMAINING SKILLS HERE]]

## Education
B.Tech in Computer Science, 2018 - 2022
This resume has well over 200 characters and describes real background facts accurately.
`;

  assert.strictEqual(isPlaceholderCv(almostReal), true);
});
