[extend]
useDefault = true

[allowlist]
description = "Global allowlist for test fixtures, mocks and example configuration"
paths = [
  '''.*\.example\..*''',
  '''env\.example''',
  '''^test/.*'''
]
regexes = [
  '''AIza.*''',
  '''gsk_.*''',
  '''super-secret.*'''
]
